import Vue from 'vue';
import Vuex from 'vuex';

Vue.use(Vuex);

export default new Vuex.Store({
  state: {
    adjectiveThemes: [
      {
        name: 'drunk synonyms',
        id: 0,
        options: [
          'addled',
          'ankled',
          'befuddled',
          'bent',
          'besotted',
          'blacked-out',
          'blasted',
          'blind',
          'blitzed',
          'blotto',
          'boiled-as-an-owl',
          'bombed',
          'buttered',
          'canned',
          'clobbered',
          'cockeyed',
          'crapulous',
          'crocked',
          'cut',
          'destroyed',
          'dipso',
          'drunk',
          'drunk-as-a-lord',
          'euphoric',
          'fried',
          'giddy',
          'gooned',
          'groggy',
          'hammered',
          'high',
          'hooched-up',
          'hung-one-on',
          'inebriated',
          'in-one\'s-cups',
          'intoxicated',
          'juiced',
          'legless',
          'liquored-up',
          'loaded',
          'looped',
          'mellow',
          'munta(d)',
          'obliterated',
          'obliviated',
          'pickled',
          'pie-eyed',
          'pissed',
          'plastered',
          'plowed',
          'plotzed',
          'polluted',
          'pot-valiant',
          'ripped',
          'roaring',
          'sauced',
          'shickered',
          'shit-faced',
          'slopped-up',
          'sloshed',
          'smashed',
          'snockered',
          'sodden',
          'soused',
          'sozzled',
          'spaced',
          'stewed',
          'stiff',
          'stinking',
          'stinko',
          'stoned',
          'swacked',
          'tanked',
          'tied-one-on',
          'three-sheets-to-the-wind',
          'tight',
          'tipsy',
          'toasted',
          'tweaked',
          'twisted',
          'under-the-influence',
          'under-the-table',
          'under-the-weather',
          'wasted',
          'wiped-out',
          'woozy',
          'wrecked',
          'zoned',
          'zonked'
        ],
      },
      {
        name: 'basic',
        id: 1,
        options: [
          'ensconced',
          'entangled',
          'enthralling',
          'entire',
          'envious',
          'eradicated',
          'eroded',
          'esoteric',
          'essential',
          'evaporated',
          'ever-present',
          'evergreen',
          'everlasting',
          'exacting',
          'exasperated',
          'excess',
          'exciting',
          'executable',
          'existent',
          'exonerated',
          'exorbitant',
          'exponential',
          'export',
          'extraordinary',
          'exultant',
          'exulting',
          'facsimile',
          'fading',
          'fainter',
          'faith-based',
          'fallacious',
          'faltering',
          'famous',
          'fancier',
          'fast-growing',
          'fated',
          'favourable',
          'fearless',
          'feathered',
          'fellow',
          'fermented',
          'ferocious',
          'fiddling',
          'filling',
          'firmer',
          'fitted',
          'flammable',
          'flawed',
          'fledgling',
          'fleshy',
          'flexible',
          'flickering',
          'floral',
          'flowering',
          'flowing',
          'foggy',
          'folic',
          'foolhardy',
          'foolish',
          'footy',
          'forehand',
          'forked',
          'formative',
          'formulaic',
          'foul-mouthed',
          'fractional',
          'fragrant',
          'fraudulent',
          'freakish',
          'freckled',
          'freelance',
          'freight',
          'fresh',
          'fretted',
          'frugal',
          'fulfilling',
          'fuming',
          'funded',
          'funny',
          'garbled',
          'gathered',
          'geologic',
          'geometric',
          'gibberish',
          'gilded',
          'ginger',
          'glare',
          'glaring',
          'gleaming',
          'glorified',
          'glorious',
          'goalless',
          'gold-plated',
          'goody',
          'grammatical',
          'grande',
          'grateful',
          'gratuitous',
          'graven',
          'greener',
          'grinding',
          'grizzly',
          'groaning',
          'grudging',
          'guaranteed',
          'gusty',
          'half-breed',
          'hand-held',
          'handheld',
          'hands-off',
          'hard-pressed',
          'harlot',
          'healing'
        ],
      },
    ],
    nounThemes: [
      {
        name: 'knights of the round table',
        id: 2,
        options: [
          'Anguish of Ireland',
          'Aristance',
          'Azreal',
          'Arrok',
          'Ascamore',
          'Balan',
          'Barrant le Apres',
          'Bellenger le Beau',
          'Belliance le Orgulous',
          'Blamor de Ganis',
          'Bleoberis de Ganis',
          'Bohart le Cure Hardy',
          'Brandiles',
          'Brian de Listinoise',
          'Carados of Scotland',
          'Cardok',
          'Chalance of Clarence',
          'Clariance of Northumberland',
          'Clarus of Cleremont',
          'Clegis',
          'Clodrus',
          'Colgrevance',
          'Crosslem',
          'Damas',
          'Degrave sans Villainy',
          'Degrevant',
          'Dinas le Seneschal de Cornwall',
          'Dinas',
          'Dodinas le Savage',
          'Dornar',
          'Drian',
          'Edward of Orkney',
          'Epinogris',
          'Fergus',
          'Florence',
          'Gahalantine',
          'Galihodin',
          'Galleron of Galway',
          'Gauter',
          'Gillimer',
          'Grummor Grummorson',
          'Gumret le Petit',
          'Harry le Fils Lake',
          'Hebes',
          'Hebes le Renowne',
          'Hectimere',
          'Helian le Blanc',
          'Herminde',
          'Hervis de la Forest Savage',
          'Ironside',
          'Kay l\'Estrange',
          'Lambaile',
          'Lambegus',
          'Lamiel',
          'Lavain',
          'Lovell',
          'Mador de la Porte',
          'Marrok',
          'Melias de l\'Isle',
          'Melion of the Mountain',
          'Meliot de Logris',
          'Menaduke',
          'Morganor',
          'Nentres of Garlot',
          'Neroveus',
          'Ozanna le Cœur Hardi',
          'Perimones',
          'Persant',
          'Pertolepe',
          'Petipace of Winchelsea',
          'Plaine de Fors',
          'Plenorius',
          'Priamus',
          'Reynold',
          'Sadok',
          'Selises of the Dolorous Tower',
          'Sentrail',
          'Severause le Breuse',
          'Suppinabiles',
          'Ulbawes',
          'Urry',
          'Villiars the Valiant'
        ],
      },
      {
        name: 'animals',
        id: 3,
        options: [
          "aardvark",
          "albatross",
          "alligator",
          "alpaca",
          "ant",
          "anteater",
          "antelope",
          "ape",
          "armadillo",
          "baboon",
          "badger",
          "barracuda",
          "bat",
          "bear",
          "beaver",
          "bee",
          "bison",
          "boar",
          "buffalo",
          "butterfly",
          "camel",
          "capybara",
          "caribou",
          "cassowary",
          "cat",
          "caterpillar",
          "cattle",
          "chamois",
          "cheetah",
          "chicken",
          "chimpanzee",
          "chinchilla",
          "chough",
          "clam",
          "cobra",
          "cockroach",
          "cod",
          "cormorant",
          "coyote",
          "crab",
          "crane",
          "crocodile",
          "crow",
          "curlew",
          "deer",
          "dinosaur",
          "dog",
          "dogfish",
          "dolphin",
          "donkey",
          "dotterel",
          "dove",
          "dragonfly",
          "duck",
          "dugong",
          "dunlin",
          "eagle",
          "echidna",
          "eel",
          "eland",
          "elephant",
          "elephant-seal",
          "elk",
          "emu",
          "falcon",
          "ferret",
          "finch",
          "fish",
          "flamingo",
          "fly",
          "fox",
          "frog",
          "gaur",
          "gazelle",
          "gerbil",
          "giant-panda",
          "giraffe",
          "gnat",
          "gnu",
          "goat",
          "goose",
          "goldfinch",
          "goldfish",
          "gorilla",
          "goshawk",
          "grasshopper",
          "grouse",
          "guanaco",
          "guinea-fowl",
          "guinea-pig",
          "gull",
          "hamster",
          "hare",
          "hawk",
          "hedgehog",
          "heron",
          "herring",
          "hippopotamus",
          "hornet",
          "horse",
          "human",
          "hummingbird",
          "hyena",
          "ibex",
          "ibis",
          "jackal",
          "jaguar",
          "jay",
          "jellyfish",
          "kangaroo",
          "kingfisher",
          "koala",
          "komodo-dragon",
          "kookabura",
          "kouprey",
          "kudu",
          "lapwing",
          "lark",
          "lemur",
          "leopard",
          "lion",
          "llama",
          "lobster",
          "locust",
          "loris",
          "louse",
          "lyrebird",
          "magpie",
          "mallard",
          "manatee",
          "mandrill",
          "mantis",
          "marten",
          "meerkat",
          "mink",
          "mole",
          "mongoose",
          "monkey",
          "moose",
          "mouse",
          "mosquito",
          "mule",
          "narwhal",
          "newt",
          "nightingale",
          "octopus",
          "okapi",
          "opossum",
          "oryx",
          "ostrich",
          "otter",
          "owl",
          "ox",
          "oyster",
          "panther",
          "parrot",
          "partridge",
          "peafowl",
          "pelican",
          "penguin",
          "pheasant",
          "pig",
          "pigeon",
          "polar-bear",
          "pony",
          "porcupine",
          "porpoise",
          "prairie-dog",
          "quail",
          "quelea",
          "quetzal",
          "rabbit",
          "raccoon",
          "rail",
          "ram",
          "rat",
          "raven",
          "red-deer",
          "red-panda",
          "reindeer",
          "rhinoceros",
          "rook",
          "salamander",
          "salmon",
          "sand-dollar",
          "sandpiper",
          "sardine",
          "scorpion",
          "sea-lion",
          "sea-urchin",
          "seahorse",
          "seal",
          "shark",
          "sheep",
          "shrew",
          "skunk",
          "snail",
          "snake",
          "sparrow",
          "spider",
          "spoonbill",
          "squid",
          "squirrel",
          "starling",
          "stingray",
          "stinkbug",
          "stork",
          "swallow",
          "swan",
          "tapir",
          "tarsier",
          "termite",
          "tiger",
          "toad",
          "trout",
          "turkey",
          "turtle",
          "vicuña",
          "viper",
          "vulture",
          "wallaby",
          "walrus",
          "wasp",
          "water-buffalo",
          "weasel",
          "whale",
          "wolf",
          "wolverine",
          "wombat",
          "woodcock",
          "woodpecker",
          "worm",
          "wren",
          "yak",
          "zebra"
        ],
      },
    ],
  },
  mutations: {},
  actions: {},
  modules: {}
});
